### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by phamlehoan** [phamlethaohien/TOEIC-Website#4]
- [ ] [Doc] Making use cases
- [ ] [Doc] Listing features and planning project
- [ ] [FEA] Designing Database
- [ ] [FEA] Initial project
     + [ ] Creating Django server
     + [ ] Creating Vue Admin app
     + [ ] Creating Vue User app
- [ ] [BE] Designing models
- [ ] [FE] Home page
- [ ] [FEA] Practicing
     + [ ] [Doc] Designing APIs
     + [ ] [BE] List questions and answers
     + [ ] [BE] Create questions and answers
     + [ ] [FE-A] List questions and answers page
     + [ ] [FE-A] Create questions and answers page
     + [ ] [BE] Get questions for praticing page
     + [ ] [FE] Practicing page
- [ ]  [FEA] Testing
     + [ ] [Doc] Designing APIs
     + [ ] [BE] Get questions for testing page
     + [ ] [FE] Testing page
- [ ]
